hotfix:
  name: test-hotfix-forwarding

streams:
  testing-devel:
    type: development
    default: true

additional_arches: [aarch64, ppc64le, s390x]

source_config:
  url: https://github.com/coreos/fedora-coreos-config

s3:
  bucket: prod-account-match-fcos-builds
  builds_key: "prod/streams/${STREAM}"
  acl: public-read

default_artifacts:
  all:
    - qemu

misc:
  allow_missing_architectures_when_autotriggering_release_job: true
  allow_skip_of_untested_artifacts: true
